### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by VanshitaGaikwad** [VanshitaGaikwad/car-price-prediction-rospl#1]
Improved documentation is required for the new users and the community to understand this machine learning model. We invite various  contributions, ideas and collaboration to do this improvements.

**Comment by gauritomar** [comment]
Hi @VanshitaGaikwad,

I wanted to let you know that I've addressed the issue you opened regarding the documentation, and I've created a pull request for it. You can find the pull request here: [PR](https://github.com/VanshitaGaikwad/car-price-prediction-rospl/pull/2).

Your feedback and suggestions would be greatly appreciated. Please take a look at the changes I've made and let me know what you think. If you have any comments or improvements to suggest, please don't hesitate to share them.

**Comment by VanshitaGaikwad** [comment]
Amazing work! highly appreciated👍
